// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


"use client"
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
      
        <Header/>
          <SessionProvider>
           <Toaster
          position="top-right"
          toastOptions={{
            duration: 3000,
            style: {
              background: "#2F2F2F",
              color: "#fff",
              borderRadius: "12px",
              padding: "14px 18px",
            },
          }}
        />
          <main>{children}</main>
          </SessionProvider>
          <Footer/>
        
        
      </body>
    </html>
  );
}